name: depup
on:
  schedule:
    - cron: "14 14 * * *"
  workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.set-matrix.outputs.files }}
    steps:
      - uses: actions/checkout@v4
      - name: Find matching README.adoc files
        id: set-matrix
        run: |
          files=$(find . -type f -name 'README.adoc' | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "files=${files}" >> "$GITHUB_OUTPUT"

  reviewdog-redpanda:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.generate-matrix.outputs.files) }}
    steps:
      - uses: actions/checkout@v4
      - name: Run reviewdog depup on ${{ matrix.file }}
        uses: reviewdog/action-depup@v1
        id: depup
        with:
          file: ${{ matrix.file }}
          version_name: latest-redpanda-version
          repo: redpanda-data/redpanda
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          commit-message: "chore(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          body: |
            Update ${{ steps.depup.outputs.repo }} to [${{ steps.depup.outputs.latest }}](https://github.com/${{ steps.depup.outputs.repo }}/releases/tag/v${{ steps.depup.outputs.latest }})

            This PR is auto generated by [depup workflow](https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}).
          branch: depup/${{ steps.depup.outputs.repo }}

  reviewdog-console:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.generate-matrix.outputs.files) }}
    steps:
      - uses: actions/checkout@v4
      - name: Run reviewdog depup on ${{ matrix.file }}
        uses: reviewdog/action-depup@v1
        id: depup
        with:
          file: ${{ matrix.file }}
          version_name: latest-console-version
          repo: redpanda-data/console
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          commit-message: "chore(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          body: |
            Update ${{ steps.depup.outputs.repo }} to [${{ steps.depup.outputs.latest }}](https://github.com/${{ steps.depup.outputs.repo }}/releases/tag/v${{ steps.depup.outputs.latest }})

            This PR is auto generated by [depup workflow](https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}).
          branch: depup/${{ steps.depup.outputs.repo }}
