name: depup
on:
  schedule:
    - cron: "14 14 * * *"
  workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.set-matrix.outputs.files }}
    steps:
      - uses: actions/checkout@v4
      - name: Find matching README.adoc files
        id: set-matrix
        run: |
          files=$(find ./docker-compose ./data-transforms -type f -name 'README.adoc' | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "files=${files}" >> "$GITHUB_OUTPUT"

  reviewdog:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.generate-matrix.outputs.files) }}
    steps:
      - uses: actions/checkout@v4
      - name: Run reviewdog depup on ${{ matrix.file }}
        uses: reviewdog/action-depup@v1
        id: depup-redpanda
        with:
          file: ${{ matrix.file }}
          version_name: latest-redpanda-version
          repo: redpanda-data/redpanda
      - name: Run reviewdog depup on console
        uses: reviewdog/action-depup@v1
        id: depup-console
        with:
          file: ${{ matrix.file }}
          version_name: latest-console-version
          repo: redpanda-data/console
      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add ${{ matrix.file }}
          git commit -m "chore(deps): update ${{ matrix.file }} to ${{ steps.depup-redpanda.outputs.latest }} and ${{ steps.depup-console.outputs.latest }}" || echo "No changes to commit"

  create-pull-request:
    needs: reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate branch name
        id: branch
        run: |
          branch_name="depup/update-all-readme-files"
          echo "branch_name=${branch_name}" >> "$GITHUB_ENV"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore(deps): update README.adoc files"
          commit-message: "chore(deps): update README.adoc files to the latest versions"
          body: |
            This PR updates all relevant README.adoc files to the latest versions of Redpanda and Redpanda Console.

            This PR is auto-generated by [depup workflow](https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}).
          branch: ${{ env.branch_name }}
